<?php return array (
  'sitename' => 'Florida RolePlay',
  'sitename_label' => 'Название вашего проекта',
  'description' => 'Проект многопользовательской модификации GTA:SA - SA:MP',
  'description_label' => 'Описание проекта (не более 256 символов)',
  'forum_url' => 'http://florida-play.esy.es/f/',
  'forum_url_label' => 'Ссылка на Ваш форум',
  'mysql_host' => 'localhost',
  'mysql_host_label' => 'Адрес базы данных сервера (хост)',
  'mysql_user' => 'root',
  'mysql_user_label' => 'Имя пользователя',
  'mysql_pass' => '',
  'mysql_pass_label' => 'Пароль',
  'mysql_dbname' => 'tester',
  'mysql_dbname_label' => 'Название базы данных',
  'editor_level' => '6',
  'editor_level_label' => 'Уровень админки для доступа к настройкам панели',
  'server_ip' => 'localhost',
  'server_ip_label' => 'Адрес вашего сервера',
  'server_port' => '7777',
  'server_port_label' => 'Порт вашего сервера',
  'server_rcon' => '89651346473',
  'server_rcon_label' => 'RCON - пароль сервера (если есть), необходим для работы консоли',
  'secret_key' => '---',
  'secret_key_label' => 'Секретный ключ проекта в системе UnitPay',
  'unitpay_action' => '---',
  'unitpay_action_label' => 'Ссылка для отправки формы',
);